name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]   # change if your default branch isn't main

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json
            server/package-lock.json

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Show repo layout (sanity check)
        run: |
          dir
          echo ==== client ====
          if exist client (dir client) else (echo client folder missing & exit 1)
          echo ==== server ====
          if exist server (dir server) else (echo server folder missing & exit 1)
          echo ==== assets ====
          if exist assets (dir assets) else (echo NOTE: assets folder missing)

      # ---------- Install deps (root, client, server) ----------
      - name: Install root deps (ci)
        run: npm ci
        continue-on-error: true
      - name: Install root deps (fallback)
        if: ${{ failure() }}
        run: npm install

      - name: Install client deps (ci)
        run: npm ci --prefix client
        continue-on-error: true
      - name: Install client deps (fallback)
        if: ${{ failure() }}
        run: npm install --prefix client

      - name: Install server deps (ci)
        run: npm ci --prefix server
        continue-on-error: true
      - name: Install server deps (fallback)
        if: ${{ failure() }}
        run: npm install --prefix server

      # ---------- Rebuild native modules for Electron (better-sqlite3) ----------
      - name: Rebuild native deps
        run: npx electron-builder install-app-deps

      # ---------- Package Windows installer (.exe) ----------
      - name: Package Windows (.exe)
        run: npm run dist
        env:
          CI: ""   # prevent CRA from failing on warnings
          DEBUG: "electron-builder"
          ELECTRON_BUILDER_LOG_LEVEL: "debug"
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      # ---------- Upload the .exe ----------
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist\*Setup*.exe
            dist\*.exe
