name: Build Windows Installer

on:
  workflow_dispatch:      # allow manual run
  push:
    branches: [ main ]    # change if your default branch is different

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show repo layout (quick debug)
        shell: pwsh
        run: |
          Write-Host "Root files:"; Get-ChildItem -Force
          Write-Host "`nclient/:"; Get-ChildItem client -Force
          Write-Host "`nserver/:"; Get-ChildItem server -Force

      # ---- Install deps (no conditionals; PowerShell-safe) ----
      - name: Install root deps
        run: npm install

      - name: Install client deps
        run: npm install --prefix client

      - name: Install server deps
        run: npm install --prefix server

      # ---- Build React (don’t fail on CRA warnings) ----
      - name: Build React
        run: npm --prefix client run build
        env:
          CI: ""

      # ---- Prepare native modules for Electron (better-sqlite3) ----
      - name: Install Electron headers
        run: npx electron-builder install-app-deps

      - name: Rebuild better-sqlite3 for Electron
        run: npx electron-rebuild -f -w better-sqlite3 --module-dir server

      # ---- Package Windows installer (.exe) ----
      - name: Package (electron-builder)
        run: npx electron-builder --win nsis
        env:
          NODE_ENV: production
          CI: ""

      - name: List dist output
        run: dir dist

      # ---- Upload the installer artifact ----
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist\*Setup*.exe
            dist\*.exe
          if-no-files-found: warn
