name: Build Windows Installer

on:
  workflow_dispatch:        # manually run from the Actions tab
  push:
    branches: [ main ]      # change if your default branch is not 'main'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json
            server/package-lock.json

      - name: Show versions
        run: |
          node -v
          npm -v

      # --- Install deps in all three places ---
      - name: Install root deps
        run: npm ci
        continue-on-error: true

      - name: Fallback root install (no lockfile)
        if: ${{ failure() }}
        run: npm install

      - name: Install client deps
        run: npm ci --prefix client
        continue-on-error: true

      - name: Fallback client install
        if: ${{ failure() }}
        run: npm install --prefix client

      - name: Install server deps
        run: npm ci --prefix server
        continue-on-error: true

      - name: Fallback server install
        if: ${{ failure() }}
        run: npm install --prefix server

      # --- Build & package ---
      # CRA can fail builds when CI=true; neutralize that here.
      - name: Build Windows installer
        run: npm run dist
        env:
          CI: ""                               # prevent CRA from treating warnings as errors
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      # --- Upload the .exe ---
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist\*Setup*.exe
            dist\*.exe
