name: Build Windows Installer

on:
  workflow_dispatch:          # manual run button
  push:
    branches: [ main ]        # ← change if your default branch isn't "main"

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Show versions
        run: |
          node -v
          npm -v
          echo "Workspace:"
          dir
          echo "client:"
          dir client
          echo "server:"
          dir server

      # ── install deps in root/client/server ──────────────────────────
      - name: Install root deps (electron, builder, etc.)
        run: |
          if exist package-lock.json (npm ci) else (npm install)

      - name: Install client deps
        run: |
          if exist client\\package-lock.json (npm ci --prefix client) else (npm install --prefix client)

      - name: Install server deps (better-sqlite3 here)
        run: |
          if exist server\\package-lock.json (npm ci --prefix server) else (npm install --prefix server)

      # ── build React ─────────────────────────────────────────────────
      - name: Build React (client)
        run: npm --prefix client run build
        env:
          CI: ""                   # don't fail on CRA warnings

      # ── prep native modules for Electron (critical for better-sqlite3) ─
      - name: Install Electron native headers
        run: npx electron-builder install-app-deps

      - name: Rebuild better-sqlite3 for Electron
        run: npx electron-rebuild -f -w better-sqlite3 --module-dir server

      # ── package Windows installer ───────────────────────────────────
      - name: Package (electron-builder)
        run: npx electron-builder --win nsis
        env:
          NODE_ENV: production
          CI: ""                   # just in case builder triggers a build step

      - name: List dist output
        run: dir dist

      # ── upload the .exe artifact ────────────────────────────────────
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            dist\*Setup*.exe
            dist\*.exe
          if-no-files-found: warn
